### ISSUE TITLE
Dude, your api is down and there is no setting to run cross-domain

### ISSUE THREAD

**Issue by gujiwuqing** [rschristian/github-contribution-calendar-api#4]
Dude, your Dude, your api is down and there is no setting to run cross-domain and there is no setting to run cross-domain

**Comment by rschristian** [comment]
I know that it's down; there's no guarantees of it always being up. I've restarted it though, should be up.

Good point on the cross domain thing though. Not sure how I want to handle that. Env var maybe?

**Comment by rschristian** [comment]
I'll push a patch tomorrow that will allow you to set the host in the CSP via an env var, so you can just start your container with the environment. Hopefully that'll be a decent solution? Thanks for letting me know though, didn't know other people were using the container.

**Comment by rschristian** [comment]
Pushed, sorry for the delay. Can set with `HOST` env var. 

Let me know if you have any more issues. I'm quite occupied with other projects, so I can't really check up to ensure everything's always working (though I try). Feel free to send me an issue or something like this and I can try to get a solution out as fast as possible. If no one reports an issue then I assume there isn't one is all. 

cc @Zfour, while I see you've now written your own, if you ever have need for this again, just let me know if you spot any issues, happy to fix them.
