### ISSUE TITLE
Support custom date ranges rather than just the previous year

### ISSUE THREAD

**Issue by 4l1fe** [rschristian/github-contribution-calendar-api#5]
Hey man, great service! I'm looking for a way to extract my contributions data and seems your service already can do it.

Can i somehow get all the years contributions from my profile by the service?

**Comment by rschristian** [comment]
Glad it's helpful! It does not support that at the moment, no, though I'd be happy to see that functionality added.

We should be able to easily support date query params, as that matches what GH does, allowing users to customize data set range. I don't think I want to support "get all the years contributions" though, as looping through the years and stitching the data together is a bit far from what it currently does.

**Comment by 4l1fe** [comment]
Ok. I'm not a JavaScript boy so can't help with it.

Anyway, that's Great you published the service!

**Comment by rschristian** [comment]
Fair enough.

I'll reopen this though, as indeed there's no way at the moment to retrieve any data set beyond the past year which is a bit of a shame considering how simple it is to support. Would like to implement that.

**Comment by 4l1fe** [comment]
Sounds good 👍

**Comment by 4l1fe** [comment]
Sounds good 👍

**Comment by 4l1fe** [comment]
Just sharing my motivation to you. I searched briefly any tool to have my data to build a custom 3d contribution heatmap.

Within a few tools I found your one looks the most promising and very easy to use.

**Comment by rschristian** [comment]
Implemented a `year` query param in 3426eddfbfaedb5e3453168c7f014e31bb8bfa0c.

As mentioned, would rather leave it up to users to piece data together themselves, but here's an example you could paste directly into your browser:

```js
let data = {};
for (let year = 2010; year < 2023; year++) {
    fetch(`https://gh-calendar.rschristian.dev/user/4l1fe?year=${year}`)
        .then(res => res.json())
        .then(res => data[year] = res);
}
```

Probably want to edit the years (or filter afterwards) but hopefully you get the idea.

**Comment by 4l1fe** [comment]
@rschristian thank you, seems i can fetch all data year by year. I've checked only single request of a previous one, it works.

And could you point me out to `count, intensity` response attributes description?

**Comment by rschristian** [comment]
I don't have those documented anywhere at the moment, though I probably should.

`count` is number of contributions and `intensity` is value 0-4 to indicate which color square that day would get. A day without any contributions would be 0, a day with the most would be 4.

Both mirror GitHub's implementation.
